language: node_js
node_js:
  - '0.10'

before_install:
  - git clone git@github.com:HabitRPG/habitrpg.git
  - cd habitrpg
  - npm install
  - cp config.json.example config.json
  - ./node_modules/.bin/grunt run:dev
  - cd ../
