language: node_js
node_js:
  - '0.10'
services:
  - mongodb

before_script:
  - 'npm install -g grunt-cli mocha grunt-karma git-changelog'
  - cd Kusold/habitrpg-api
  - seedHabitRPGMongo.sh
  - startHabitRPGServer.sh
